[package]
name = "rsftch"
version = "0.5.0"
edition = "2021"
authors = ["Charklie charliejohanid@gmail.com"]
license = "MIT"
description = "Lightning fast hardware fetch tool written in rust."
readme = "README.md"
repository = "https://github.com/charklie/rsftch"
keywords = ["fetch", "rust", "neofetch"]
categories = ["command-line-utilities"]

[dependencies]
colored = "2.1.0"
figlet-rs = "=0.1.5"
libmacchina = "7.2.2"
rayon = "1.10.0"
